### ISSUE TITLE
Draft attachments disappearing

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#124]
Postup: nova ziadost / pridat attachment / save / load / save / load / submit -> error

```
[2015-12-18 08:02:51,798] django.request ERROR Internal Server Error: /sk/infoziadosti/nova-ziadost/3/
Traceback (most recent call last):
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/allauth/account/decorators.py", line 33, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/views/inforequest.py", line 83, in inforequest_create
    inforequest.save()
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/inforequest.py", line 482, in save
    super(Inforequest, self).save(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/models.py", line 34, in __call__
    self.func(model)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/inforequest.py", line 455, in deferred
    branch.save()
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/branch.py", line 324, in save
    super(Branch, self).save(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/models.py", line 34, in __call__
    self.func(model)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/branch.py", line 313, in deferred
    action.save()
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 626, in save_base
    update_fields=update_fields, raw=raw, using=using)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/models.py", line 34, in __call__
    self.func(model)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/models/action.py", line 466, in deferred
    attachment = attch.clone(action)
  File "/var/www/chcemvediet/chcemvediet/poleno/attachments/models.py", line 115, in clone
    file=ContentFile(self.content),
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/utils/functional.py", line 55, in __get__
    res = instance.__dict__[self.func.__name__] = self.func(instance)
  File "/var/www/chcemvediet/chcemvediet/poleno/attachments/models.py", line 92, in content
    self.file.open(u'rb')
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/fields/files.py", line 79, in open
    self.file.open(mode)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/fields/files.py", line 49, in _get_file
    self._file = self.storage.open(self.name, 'rb')
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/files/storage.py", line 35, in open
    return self._open(name, mode)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/files/storage.py", line 172, in _open
    return File(open(self.path(name), mode))
IOError: [Errno 2] No such file or directory: u'/var/www/chcemvediet/chcemvediet/media/attachments/lLgb9u2P6C'
```

A naozaj subor "attachments/lLgb9u2P6C" neexistuje, hoci referencia na neho existuje.

**Comment by mmmaly** [comment]
konkretny specimen na ch2.labs - vola sa to prilohy 5


IOError at /en/infoziadosti/nova-ziadost/8/
[Errno 2] No such file or directory:
u'/var/www/clients/client5/web14/private/chcemvediet/media/attachments/eYRQ3qL6Uh'

**Comment by mmmaly** [comment]
Postup: Najprv som natahal kopec nulovych
suborov. Potom som chcel pridat nejaky velky, ten mi nepridalo, tak
som skusal postupne mensie velkosti. A potom zrazu vyhucalo, ze
niektory z predoslych neexistuje.

**Comment by martinmacko47** [comment]
Najprv treba spravit #130, nech vieme, ci sa subory vobec nahrali.

**Comment by martinmacko47** [comment]
Dependency vyriesena

**Comment by martinmacko47** [comment]
Oprava je priamo v branchi ``master``

Postup: nova ziadost / pridat attachment / save / load / save / load / submit -> funguje

@mmmaly: pls otestuj, ze hore uvedeny postup naozaj funguje. Ak si pamatas postup, ako sa Ti podarilo dostat k chybe v https://github.com/martinmacko47/chcemvediet/issues/124#issuecomment-167292045 tak to tiez otestuj. Ak najdes dalsie bugy s prilohami, pls, sprav pre ne samostatne issues.

Po deploy treba pozriet ktore prilohy sa nam stratili a vyriesit to nejak vhodne rucne. Zoznam stratenych priloh sa da najst pomocou:
```
env/bin/python manage.py datacheck
```
Na dev1 a dev2 serveroch som stratene prilohy nahradil prazdnymi subormi, nech nehadzu chyby, ked sa ich niekto pokusi downloadnut.
