### ISSUE TITLE
 cronjob error: (admin.E035) The value of 'readonly_fields[0]' is not a callable

### ISSUE THREAD

**Issue by mmmaly** [martinmacko47/chcemvediet#129]
Pri testovani smail dispatchera cron zacal hlasit taketo veci:

CommandError: System check identified some issues:

ERRORS:
<class 'chcemvediet.apps.geounits.admin.NeighbourhoodAdmin'>: (admin.E035) The value of 'readonly_fields[0]' is not a callable, an attribute of 'NeighbourhoodAdmin', or an attribute of 'geounits.Neighbourhood'.

asi to s tym nesuvisi, ale pre istotu otvaram. Bola to cista vetva, akurat som spustal druhykrat setup.py aby som zmenil z 1 (no emails) na 2 (dummy).

**Comment by mmmaly** [comment]
aha, to som asi sposobil tymto:

Imported ObligeeAlias: 74 created, 0 changed, 0 unchanged and 0 marked for deletion
Warning: <Neighbourhood: [1] dummy> was omitted. All the following related items will be deleted with it:
	-- Neighbourhood: <Neighbourhood: [1] dummy>
Are you sure, you want to delete it? Yes/No/Abort [N]: y
Warning: <Municipality: [1] dummy> was omitted. All the following related items will be deleted with it:
	-- Municipality: <Municipality: [1] dummy>
Are you sure, you want to delete it? Yes/No/Abort [N]: y
Warning: <District: [1] dummy> was omitted. All the following related items will be deleted with it:
	-- District: <District: [1] dummy>
Are you sure, you want to delete it? Yes/No/Abort [N]: y
Warning: <Region: [1] dummy> was omitted. All the following related items will be deleted with it:
	-- Region: <Region: [1] dummy>
Are you sure, you want to delete it? Yes/No/Abort [N]: y
Done.

Ale neviem, preco sa ma to pytalo.

**Comment by martinmacko47** [comment]
Z rovnakeho dovodu vznika zrejme aj tato chyba, ked sa v adminovi otvori detail ``neighbourhood``:
```
[2016-01-01 16:33:29,140] django.request ERROR Internal Server Error: /en/admin/geounits/neighbourhood/20008/
Traceback (most recent call last):
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 137, in get_response
    response = response.render()
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/response.py", line 103, in render
    self.content = self.rendered_content
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/response.py", line 80, in rendered_content
    content = template.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 126, in render
    return compiled_parent._render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 201, in render
    nodelist.append(node.render(context))
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/loader_tags.py", line 150, in render
    return template.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 148, in render
    return self._render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 142, in _render
    return self.nodelist.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/base.py", line 844, in render
    bit = self.render_node(node, context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/debug.py", line 80, in render_node
    return node.render(context)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 201, in render
    nodelist.append(node.render(context))
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/template/defaulttags.py", line 161, in render
    values = list(values)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 103, in __iter__
    model_admin=self.model_admin)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/contrib/admin/helpers.py", line 150, in __init__
    label = label_for_field(field, form._meta.model, model_admin)
  File "/home/martin/projekty/00.moje/2013-09-23.chcemvediet/chcemvediet/env/local/lib/python2.7/site-packages/django/contrib/admin/utils.py", line 324, in label_for_field
    raise AttributeError(message)
AttributeError: Unable to lookup 'slug' on Neighbourhood or NeighbourhoodAdmin

```

**Comment by martinmacko47** [comment]
Chyba bola v tom, ze ``Neighbourhood`` nema field ``slug``, ale v admin ostalo, ze ho ma mat.

Povodnu reportovanu chybu sa mi nepodarilo zreplikovat, lebo https://code.djangoproject.com/ticket/23497 v Django 1.7 este fixnute nebolo. Ak si spomenies ako sa Ti tu chybu podarilo najst, mozes skusit, ci v branchi ``neighbourhood_admin`` uz nenastava. Chyba, co som pastol o comment vyssie uz nenastava.

To co si popisoval v https://github.com/martinmacko47/chcemvediet/issues/129#issuecomment-167227070 som nepochopil. Ale nevyzera, zeby to malo suvis s tymto. Ak si spomenies, ako to vzniklo, tak sprav novy issue, a popis podrobne, co sa stalo.

**Comment by mmmaly** [comment]
skusil som zreprodukovat na aktualnej deploy branch (cize tej, ktora nas trapi). Urobil som to co vtedy, prepol setup.py z 1 na 2, ale neurobilo to nic zle. Mozno na to bola treba nejaka exoticka konfiguracia db a kodu.
Tak nateraz zatvaram, ak by sa to znova vyskytlo, tak znovu otvorim.

**Comment by martinmacko47** [comment]
Chyba
```
ERRORS:
: (admin.E035) The value of 'readonly_fields[0]' is not a callable, an attribute of 'NeighbourhoodAdmin', or an attribute of 'geounits.Neighbourhood'.
```
bola skutocna, ale koli inej chybe v Djangu, sa ten test, co nepresiel, spusti iba niekedy. Netusim kedy. Branch ``neighbourhood_admin`` som teda mergol do deploy.
