### ISSUE TITLE
Pada mandrill webhook

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#367]
```
[2021-04-10 16:39:23,298] django.request ERROR Internal Server Error: /mandrill/webhook/
Traceback (most recent call last):
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/views.py", line 78, in wrapped_view
    return view(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/poleno/mail/transports/mandrill/views.py", line 66, in webhook
    webhook_event.send(sender=None, event_type=event[u'event'], data=event)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/chcemvediet/chcemvediet/poleno/mail/transports/mandrill/signals.py", line 88, in inbound_email_webhook_event
    message.save()
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x9A\\xB6\\xF0\\x9F...' for column 'text' at row 1"
```

**Comment by martinmacko47** [comment]
```
[2021-04-10 16:39:23,298] django.request ERROR Internal Server Error: /mandrill/webhook/
Traceback (most recent call last):
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/csrf.py", line 57, in wrapped_view
    return view_func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/views.py", line 78, in wrapped_view
    return view(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/transaction.py", line 394, in inner
    return func(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/poleno/mail/transports/mandrill/views.py", line 66, in webhook
    webhook_event.send(sender=None, event_type=event[u'event'], data=event)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/dispatch/dispatcher.py", line 198, in send
    response = receiver(signal=self, sender=sender, **named)
  File "/var/www/chcemvediet/chcemvediet/poleno/mail/transports/mandrill/signals.py", line 88, in inbound_email_webhook_event
    message.save()
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 589, in save
    force_update=force_update, update_fields=update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 617, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 698, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/base.py", line 731, in _do_insert
    using=using, raw=raw)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/manager.py", line 92, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/query.py", line 921, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/models/sql/compiler.py", line 920, in execute_sql
    cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/utils.py", line 94, in __exit__
    six.reraise(dj_exc_type, dj_exc_value, traceback)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/utils.py", line 65, in execute
    return self.cursor.execute(sql, params)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/db/backends/mysql/base.py", line 129, in execute
    return self.cursor.execute(query, args)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/MySQLdb/cursors.py", line 205, in execute
    self.errorhandler(self, exc, value)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/MySQLdb/connections.py", line 36, in defaulterrorhandler
    raise errorclass, errorvalue
OperationalError: (1366, "Incorrect string value: '\\xF0\\x9F\\x9A\\xB6\\xF0\\x9F...' for column 'text' at row 1"
```

**Comment by martinmacko47** [comment]
@mmmaly Pls otestuj fix v PR https://github.com/martinmacko47/chcemvediet/pull/368

Pri testovani najprv vykonaj ukony v popise PR, potom chechoutni danu branchu. A vyskusaj spravit ziadost, kde bude 🚶🏻. Ci sa ho podari do DB ulozit, alebo nie.
