### ISSUE TITLE
Neohandlovane downloadovanie unsuccessful attachment finalization

### ISSUE THREAD

**Issue by martinmacko47** [martinmacko47/chcemvediet#375]
Ked niekto rucne zada URL s ID unsuccessful `AttachmentFinalization`, tak by mu to malo dat error 404. Namiesto toho mu to ten subor da ak existuje, alebo volanie padne na:

```
[2021-04-24 18:28:03,363] django.request ERROR Internal Server Error: /sk/infoziadosti/prilohy-anonymizovane/903/
Traceback (most recent call last):
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/var/www/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/django/views/decorators/http.py", line 41, in inner
    return func(request, *args, **kwargs)
  File "/var/www/chcemvediet/chcemvediet/chcemvediet/apps/inforequests/views/attachment.py", line 72, in attachment_finalization_download
    return attachments_views.download(request, attachment_finalization, filename)
  File "/var/www/chcemvediet/chcemvediet/poleno/attachments/views.py", line 35, in download
    return send_file_response(request, path, filename or attachment.name, attachment.content_type)
  File "/var/www/chcemvediet/chcemvediet/poleno/utils/http.py", line 37, in send_file_response
    raise OSError(u'Not a regular file: {}'.format(path))
OSError: Not a regular file: /var/www/chcemvediet/chcemvediet/media/
```

Je to sposobene tym, ze `AttachmentFinalization.file.name` je pre taketo instancie prazdny string, takze
`path = os.path.join(settings.MEDIA_ROOT, attachment.file.name)` pouzite v `download` view je adresar, kde su subory.

Treba to fixnut tak, ze `download` view vrati 404, ak `attachment.file.name` je prazdne. A asi aj ak prazdne nie je, ale dany subor fyzicky neexistuje.

Okrem toho treba fixnut aj `attachment_finalization_download` view, nech vrati 404 aj ked `AttachmentFinalization` je unsuccessful. Pre pripad, ked dana instancia ma nejaky subor, ale je unsuccessful, nech ten subor nezverejnujeme.

V admin rozhrani mozeme dovolit stiahnut vsetky existujuce subory, takze tam check, ci je instancia successful netreba.

Okrem toho pls prejdi vsetky pripady, kde sa `download` view pouziva, a pozri, ci tam nemame rovnaky bug niekde. Ze dovolujeme stihanut subor, ktory nechceme dovolit stiahnut. Ak ano, tak to treba tiez ohandlovat.

**Comment by martinmacko47** [comment]
@viliambalaz Hm. Na druhe zamyslenie:

Asi nie je dobre osetrovat vynimky vo vseobecnom viewe `poleno.attachments.views.download`. Vseobecny view by mal asi naozaj raisnut povodnu exception, ktora pri posielani suboru nastala. Rovnako ako neriesi, ci user ma pravo dany subor stiahnut a podobne.

To by mal riesit az specificky view, ktory tento vseobecny view pouziva. Teda `attachment_finalization_download` by malo overit, ze attachment finalization je successful, a vseobecny view zavolat iba vtedy. Navyse, ak attachment finalization je successful, tak by mal platit invariant, ze v takom pripade attachment finalization ma neprazdne `file.name` a dany subor aj existuje. Cize je dobre, ze v pripade, ak attachment finalization je successful a subor neexistuje, teda je poruseny invariant, tak request skonci na 500. Vdaka tomu nam zaloguje error a budeme moct zistit, preco je attachment finalization oznaceny ako successful a nema funkcny subor.

Podobne admin download view `DownloadAdminMixin.download_view` by mal osetrit, ci stahovany attachment-like objekt ma `file.name`. A vseobecny view by mal zavolat iba ak ho ma.

**Malo by sa to spravat cca nejak takto:**

`attachment_finalization_download`:

| finalization je successful | file.name ma hodnotu | subor existuje | vysledok |
|-|-|-|-|
| nie | ano | ano | 404 *) |
| nie | ano | nie | 404 *) |
| nie | nie | --  | 404 *) |
| ano | ano | ano | ok  |
| ano | ano | nie | 500 |
| ano | nie | --  | 500 |

`DownloadAdminMixin.download_view`:

| finalization je successful | file.name ma hodnotu | subor existuje | vysledok |
|-|-|-|-|
| nie | ano | ano | ok  |
| nie | ano | nie | 500 |
| nie | nie | --  | 404  *) |
| ano | ano | ano | ok  |
| ano | ano | nie | 500 |
| ano | nie | --  | 404 *) |

*) Na webe / v admin rozhrani by nemala byt pren download linka

Skus pls spravit separatny PR, kde to implementujes tak, ako je popisane v tomto commente. Povodny PR zatial pre istotu nechaj, ak by sme sa potrebovali k nemu vratit.

**Comment by martinmacko47** [comment]
Este treba doriesit, ze ked vieme, ze linka na `AttachmentFinalization` skonci so 404, tak tu linku ani nezobrazit.

a) Vo zverejnenej ziadosti: Malo by sa to spravat, ako keby dany `AttachmentFinalization` ani neexistoval.

b) V admin rozhrani. V admin rozhrani je ta linka sice neviditelna, kedze je prazdny nazov suboru. Ale zislo by sa, aby ta linka tam vobec ani nebola. To by sa dalo vyriesit upravou `admin_obj_format`. Aby ked obsah linky `res` je prazdny, tak by sa vypisalo iba `--`, podobne ako ked je `obj` nedefinovane.
