### ISSUE TITLE
Pada setup.py na githube pri Testing project workflow

### ISSUE THREAD

**Issue by viliambalaz** [martinmacko47/chcemvediet#420]
```
Downloading Fontello:

$ env/bin/python fontello/fontello.py

Fontello: Uploading config.json...
Traceback (most recent call last):
  File "fontello/fontello.py", line 26, in <module>
    response = requests.post(FONTELLO_HOST, files=dict(config=config))
  File "/home/runner/work/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/requests/api.py", line 99, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/home/runner/work/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/requests/api.py", line 49, in request
    response = session.request(method=method, url=url, **kwargs)
  File "/home/runner/work/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/requests/sessions.py", line 461, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/runner/work/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/requests/sessions.py", line 573, in send
    r = adapter.send(request, **kwargs)
  File "/home/runner/work/chcemvediet/chcemvediet/env/lib/python2.7/site-packages/requests/adapters.py", line 431, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)
Traceback (most recent call last):
  File "setup.py", line 652, in <module>
    main()
  File "setup.py", line 620, in main
    download_fontello(configure)
  File "setup.py", line 291, in download_fontello
    call(u'Downloading Fontello:', [u'env/bin/python', u'fontello/fontello.py'])
  File "setup.py", line 38, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/python', u'fontello/fontello.py']' returned non-zero exit status 1
Traceback (most recent call last):
  File "setup.py", line 652, in <module>
    main()
  File "setup.py", line 608, in main
    call(u'Rerunning with: env/bin/python', [u'env/bin/python', u'setup.py']);
  File "setup.py", line 38, in call
    return subprocess.check_call(args, cwd=cwd)
  File "/opt/hostedtoolcache/Python/2.7.18/x64/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[u'env/bin/python', u'setup.py']' returned non-zero exit status 1
Error: Process completed with exit code 1.
```

**Comment by martinmacko47** [comment]
@viliambalaz Problem bol v SSL cerifikate. Zrejme mame prilis staru verziu pythonu alebo nejakej kniznice, ktora novy certifikat uz nevie overit. Ako workarround som nateraz overovanie cerifikatu vypol. Ked dopiseme testy a potom vsetko upgradneme, workarround vyhodime.
